[package]
name = "dgrlin"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "dgrlin"
crate-type = ["cdylib"]

[dependencies]
eyre = "0.6.12"
hex = "0.4.3"
pyo3 = "0.24.0"
serde = "1.0.219"
